### PR TITLE
Add Laravel 11 compatibility

### PR DESCRIPTION
**Pull request by daun**
Hi! I just tried to install the package into a Laravel 11 project and it looks like the composer.json needs an update for that.

### CODE REVIEW

**Comment by daun** [comment]
Nevermind, this actually won't work in Laravel 11 and will need a bit of a rewrite :)

**Comment by daun** [comment]
I needed this somewhat urgently and hacked together a generic configurable [uptime ping package](https://github.com/daun/laravel-uptime-ping) that works with the new Laravel 11 console kernel changes. For what it's worth, you might find the Laravel 11 parts in there useful :)

**Comment by sebastianpopp** [comment]
Thank you for your help! I figured out a way to support 10.x and 11.x, so the package should be compatible with both versions now.

**Comment by daun** [comment]
Amazing, thanks for your work maintaining this. Now I'm in the awkward position of having written a custom package when I could have just waited until Monday 🙃 That's how it goes with tight deadlines sometimes...

**Pull request closed without merging**
